import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { getServerSession } from "next-auth";
import Provider from "@/components/Provider";
import { getDirection, getTranslations } from "@/lib/intl";
import { Locale, i18n } from "../../../i18n-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  params,
  children,
}: {
  params: { locale: Locale };
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  const { locale } = params;

  const t = await getTranslations(locale);

  const dir = getDirection(locale);

  return (
    <html lang={locale} dir={dir}>
      <body className={inter.className}>
        <Provider>
          <div className={`flex ${session?.user == undefined && "flex-col"}`}>
            {session?.user == undefined ? (
              <Navbar t={t?.["header"]} locale={locale} />
            ) : (
              <Sidebar t={t} locale={locale} />
            )}
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
